---
title: "Project Two_BreastCancer"
output: word_document
---

```{r setup, include=FALSE}


library(mlbench)
data("BreastCancer")

BreastCancer <- na.omit(BreastCancer) 

BreastCancer$Id <- NULL 
```

#Libraries
```{r Libraries}
#install.packages("klaR") #install if required 
library(MASS)
library(klaR)
library(e1071) #for SVM
library(nnet)
library(rpart)
library(randomForest)
```



```{r Data Prep}
#observing categories in Class
table(BreastCancer$Class)
```

```{r}
BreastCancer$Class <- ifelse(BreastCancer$Class == 'malignant', 1,0)
BreastCancer$Class <- as.factor(BreastCancer$Class)
str(BreastCancer)
```



```{r SVM}
mysvm <- svm(Class ~ ., BreastCancer)
mysvm.pred <- predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Class)
```



```{r Naive Bayse}
mynb <- NaiveBayes(Class ~ ., BreastCancer)
mynb.pred <- predict(mynb,BreastCancer)
table(mynb.pred$class,BreastCancer$Class)
```


```{r Neural Network}
mynnet <- nnet(Class ~ ., BreastCancer, size=1)
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
table(mynnet.pred,BreastCancer$Class)
```



```{r Decision Tree}
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree) # in "BreastCancer_tree.ps"
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)
```


```{r LOOCV}
ans <- numeric(length(BreastCancer[,1]))
for (i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~ ., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
```


```{r Convert to Numeric}
bcnum.df <- BreastCancer
cols.num <- c("Cl.thickness", "Cell.size", "Cell.shape", "Marg.adhesion", "Epith.c.size", "Bare.nuclei", "Bl.cromatin", "Normal.nucleoli", 
"Mitoses")
#converting all categorical values to numeric
bcnum.df[cols.num] <- sapply(bcnum.df[cols.num],as.numeric)
#checking the class of all variables
sapply(bcnum.df, class)
```


```{r QDA}
#library(MASS)
myqda <- qda(Class ~ ., bcnum.df)
myqda.pred <- predict(myqda, bcnum.df)
table(myqda.pred$class,bcnum.df$Class)
```



```{r RDA}
#library(klaR)
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)
table(myrda.pred$class,BreastCancer$Class)
```



```{r Random Forets}
#library(randomForest)
myrf <- randomForest(Class ~ .,BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
table(myrf.pred, BreastCancer$Class)
```

```{r}
combine.classes<-data.frame(myrf.pred, myrda.pred$class,#myqda.pred,
mytree.pred,mynnet.pred,mysvm.pred, mynb.pred$class)
#head(combine.classes)
#head(myrf.pred)
#head(myrda.pred)
combine.classes$myrf.pred<-ifelse(combine.classes$myrf.pred=="benign", 0, 1)
combine.classes[,2]<-ifelse(combine.classes[,2]=="benign", 0, 1)
combine.classes[,3]<-ifelse(combine.classes[,3]=="benign", 0, 1)
combine.classes[,4]<-ifelse(combine.classes[,4]=="benign", 0, 1)
combine.classes[,5]<-ifelse(combine.classes[,5]=="benign", 0, 1)
combine.classes[,6]<-ifelse(combine.classes[,6]=="benign", 0, 1)
```


```{r}
majority.vote=rowSums(combine.classes)
head(majority.vote)
```

```

